import type { DashboardData } from "./types";

export const fallbackDashboardData: DashboardData = {
  userId: "demo-user",
  date: "2026-07-11",
  source: "fallback",
  practices: [
    {
      id: "practice-qigong",
      userId: "demo-user",
      title: "Цигун",
      description: "Мягкая утренняя практика для пробуждения тела.",
      category: "Тело",
      defaultDurationMinutes: 45,
      color: "#688b76",
      icon: "leaf",
      image: {
        kind: "builtin",
        ref: "/images/categories/qigong.jpg",
      },
      source: "manual",
      notes: "",
      archived: false,
    },
    {
      id: "practice-pranayama",
      userId: "demo-user",
      title: "Пранаяма",
      description: "Дыхательная практика для выравнивания ритма.",
      category: "Дыхание",
      defaultDurationMinutes: 20,
      color: "#7f8467",
      icon: "wind",
      image: {
        kind: "builtin",
        ref: "/images/categories/pranayama.jpg",
      },
      source: "manual",
      notes: "",
      archived: false,
    },
    {
      id: "practice-reading",
      userId: "demo-user",
      title: "Чтение",
      description: "Небольшой блок чтения материалов по практике.",
      category: "Текст",
      defaultDurationMinutes: 25,
      color: "#7a6b5f",
      icon: "book",
      image: {
        kind: "builtin",
        ref: "/images/categories/reading.jpg",
      },
      source: "manual",
      notes: "",
      archived: false,
    },
  ],
  schedule: {
    id: "schedule-1",
    userId: "demo-user",
    date: "2026-07-11",
    source: "manual",
    title: "Спокойный день",
    items: [
      {
        id: "scheduled-1",
        practiceId: "practice-qigong",
        plannedDate: "2026-07-11",
        plannedStartTime: "07:30",
        plannedDurationMinutes: 45,
        order: 0,
        status: "completed",
      },
      {
        id: "scheduled-2",
        practiceId: "practice-pranayama",
        plannedDate: "2026-07-11",
        plannedStartTime: "13:00",
        plannedDurationMinutes: 20,
        order: 1,
        status: "planned",
      },
      {
        id: "scheduled-3",
        practiceId: "practice-reading",
        plannedDate: "2026-07-11",
        plannedStartTime: "21:00",
        plannedDurationMinutes: 25,
        order: 2,
        status: "planned",
      },
    ],
  },
  diary: [
    {
      id: "entry-1",
      userId: "demo-user",
      practiceId: "practice-qigong",
      scheduledPracticeId: "scheduled-1",
      kind: "text",
      createdAt: "2026-07-11T08:25:00.000Z",
      updatedAt: "2026-07-11T08:25:00.000Z",
      text: "После практики тело стало заметно мягче, дыхание ровное.",
      voiceFileId: null,
      transcription: null,
    },
  ],
  statistics: {
    period: "week",
    totalMinutes: 255,
    totalHours: 4.25,
    completedCount: 8,
    skippedCount: 1,
    movedCount: 1,
    completionPercent: 80,
    streakDays: 6,
    favoritePracticeIds: ["practice-pranayama"],
  },
};
